Begin afredo refactoring (@rCamposCruz, @ericghlee, @gustavocovas)

diff --git a/script/alfredo b/script/alfredo
--- a/script/alfredo
+++ b/script/alfredo
@@ -6,8 +6,6 @@
 # (requires docker, docker-compose and sudo privileges)
 #
 
-DOCKER='docker'
-DOCKER_COMPOSE='docker-compose'
 GEMS='Gemfile'
 
 function usage {
@@ -31,81 +29,31 @@ function usage {
 }
 function check_deps {
     # Check dependencies.
-    command -v ${DOCKER}>/dev/null 2>&1 || { echo >&2 "I require '${DOCKER}', but it's not installed.  Aborting."; exit 1; }
-    command -v ${DOCKER_COMPOSE}>/dev/null 2>&1 || { echo >&2 "I require '${DOCKER_COMPOSE}', but it's not installed.  Aborting."; exit 1; }
+    command -v docker > /dev/null 2>&1 || { echo >&2 "I require '${DOCKER}', but it's not installed.  Aborting."; exit 1; }
+    command -v docker-compose > /dev/null 2>&1 || { echo >&2 "I require '${DOCKER_COMPOSE}', but it's not installed.  Aborting."; exit 1; }
     return 0
 }
-function app_seed {
-    sudo ${DOCKER_COMPOSE} run web rake db:seed                 # Seeds the database.
-    sudo ${DOCKER_COMPOSE} run web rake db:seed RAILS_ENV=test  # Seeds the test database.
-}
-function app_restart {
-    sudo ${DOCKER} stop $(sudo ${DOCKER} ps -a -q)              # Stops old containers.
-    sudo ${DOCKER_COMPOSE} up                                   # Starts the app.
-}
-function app_migrate {
-    sudo ${DOCKER_COMPOSE} run web rake db:create               # Creates all databases.
-    sudo ${DOCKER_COMPOSE} run web rake db:migrate              # Runs migrations.
-}
-function app_cucumber {
-    app_migrate
-    sudo ${DOCKER_COMPOSE} run web ./script/cucumber            # Runs acceptance tests.
-}
-function app_rspec {
-    app_migrate
-    sudo ${DOCKER_COMPOSE} run web rake spec                    # Runs rspec tests.
-}
-function app_test {
-    app_migrate
-    sudo ${DOCKER_COMPOSE} run web rake spec                    # Runs unity tests.
-    sudo ${DOCKER_COMPOSE} run web ./script/cucumber            # Runs acceptance tests.
-}
-function app_db {
-    sudo ${DOCKER_COMPOSE} run db psql -U postgres -h db
-}
-function app_db_reset {
-    sudo ${DOCKER_COMPOSE} run web rake db:reset
-}
-function app_run {
-    app_migrate
-    if [[ -f ./tmp/pid/server.pid ]]
-    then
-        sudo rm ./tmp/pid/server.pid
-    fi
-    sudo ${DOCKER_COMPOSE} up                                   # Starts the app.
-}
-function build_update {
-    sudo ${DOCKER_COMPOSE} run web bundle update                # Updating gems.
-    app_test
-}
-function build_clean {
-    CONTAINERS=$(sudo ${DOCKER} ps -a -q)
-    if [[ -n $CONTAINERS ]] 
-    then
-        sudo ${DOCKER} stop $CONTAINERS # Stops old containers.
-        sudo ${DOCKER} rm $CONTAINERS   # Remove old containers.
-    fi
-    if [[ -f ./tmp/pid/server.pid ]]
-    then
-        sudo rm ./tmp/pid/server.pid
-    fi
-}
-function build_purge {
-    build_clean
-    PROJECT_DIR=${PWD##*/}                         # Gets current dir name.
-    if [[ -f ${GEMS}.lock ]]
-    then
-        rm ${GEMS}.lock                                # Purges the lock.
-    fi
-    sudo ${DOCKER} rmi ${PROJECT_DIR}_web:latest   # Removes old project image.
-}
-function build {
-    build_purge
 
-    sudo ${DOCKER_COMPOSE} build                   # Builds a new image.
-    sudo ${DOCKER_COMPOSE} run web rake db:seed    # Adds admin user.
-    app_test
+function build
+{
+    docker-compose build
 }
+
+function migrate
+{
+    docker-compose run web rake db:migrate
+}
+
+function seed
+{
+    docker-compose run web rake db:seed
+}
+
+function run
+{
+    docker-compose up
+}
+
 
 if check_deps; then
     if [[ $1 == build ]]; then build;
@@ -113,14 +61,14 @@ if check_deps; then
     elif [[ $1 == update ]]; then build_update;
     elif [[ $1 == clean ]]; then build_clean;
     elif [[ $1 == restart ]]; then app_restart;
-    elif [[ $1 == run ]]; then app_run;
+    elif [[ $1 == run ]]; then run;
     elif [[ $1 == db ]]; then app_db;
     elif [[ $1 == db:reset ]]; then app_db_reset;
-    elif [[ $1 == migrate ]]; then app_migrate;
+    elif [[ $1 == migrate ]]; then migrate;
     elif [[ $1 == cucumber ]]; then app_cucumber;
     elif [[ $1 == rspec ]]; then app_rspec;
     elif [[ $1 == test ]]; then app_test;
-    elif [[ $1 == seed ]]; then app_seed;
+    elif [[ $1 == seed ]]; then seed;
     elif [[ $1 == help ]]; then usage;
     else { echo ""; echo "Error: no valid argument."; echo ""; usage; echo "Exiting..."; exit 0; }
     fi
